image: docker:cli
services:
    - docker:dind
variables:
    DOCKER_DRIVER: overlay2
    COMPOSE_HTTP_TIMEOUT: 200 #incase of slow startup

stages:
    - build
    - test

build:
    stage: build
    script:
        - echo "building system image..."
        - docker build -t aki-system:$CI_COMMIT_BRANCH .
        - docker images  # List images to verify build success

test:
    stage: test
    script:
        - echo "tests not implemented yet..."
    