image: python:3.12

stages:
    - build
    - test

install_dependencies:
    stage: build
    script:
        - echo "Building python virtual environment..."
        - python -m venv venv
        - source venv/bin/activate
        - pip install -r requirements.txt
        - pip install coverage "also add coverage for tests"
        - echo "python virtual environment built!"
    artifacts:
        paths:
            - venv/ # so venv survives across stages
        expire_in: 1h
    tags:
        - shared # use DoC shared runners

run-tests:
    stage: test
    script:
        - echo "running unittests"
        - source /venv/bin/activate
        - make unittest
    dependencies:
        - install_dependencies
    tags:
        - shared # use DoC shared runners
    
    