version: '3.8'

services:
  db:
    container_name: db
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hospital_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'  # Consider removing if not needed externally
    command: --local-infile=1
    volumes:
      - my-db:/var/lib/mysql
      - ./database/dump.sql:/docker-entrypoint-initdb.d/dump.sql
    networks:
      - my_network  
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      interval: 10s
      timeout: 5s
      retries: 3

  message-simulator:
    build:
      context: ./simulation
      dockerfile: Dockerfile.simulation
    container_name: message_sim
    networks:
      - my_network
    depends_on:
      aki-system:
        condition: service_started
    ports:
      - "8440:8440"
      - "8441:8441"
    logging:
      driver: "local"
    volumes:
      - ./logs:/var/log

  aki-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aki-system
    networks:
      - my_network
    depends_on:
      db:
        condition: service_healthy  # Ensure db is ready before aki-system starts
    logging:
      driver: "local"
    volumes:
      - ./logs:/var/log

volumes:
  my-db:

networks:
  my_network:
    driver: bridge
