services:
  message-simulator:
    build:
      context: ./simulation
      dockerfile: Dockerfile.simulation
    container_name: message_sim
    networks:
      - my_network
    depends_on:
      - aki-system
    ports:
      - "8440:8440"
      - "8441:8441"
    logging:
      driver: "local"
    volumes:
      - ./logs/simulation.log:/var/log/simulation.log
      - ./simulation:/var/simulation

  aki-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aki-system
    networks:
      - my_network
    logging:
      driver: "local"
    volumes:
      - ./logs/aki-system.log:/var/log/aki-system.log

networks:
  my_network:
    driver: bridge
