
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: aki-detection-state
  namespace: europe
spec:
  accessModes:
    - ReadWriteOnce
  storageClassName: managed-csi
  resources:
    requests:
      storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: mysql
  namespace: europe
spec:
  selector:
    app: mysql
  ports:
    - port: 3306
      targetPort: 3306
  type: ClusterIP
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mysql
  namespace: europe
spec:
  replicas: 1
  selector:
    matchLabels:
      app: mysql
  template:
    metadata:
      labels:
        app: mysql
    spec:
      containers:
      - name: mysql
        image: mysql:8.0
        command:  # Specify the command if needed
        env:
          - name: MYSQL_ROOT_PASSWORD
            value: "password"
          - name: MYSQL_DATABASE
            value: "hospital_db"
          - name: MYSQL_USER
            value: "user"
          - name: MYSQL_PASSWORD
            value: "password"
        ports:
          - containerPort: 3306
        volumeMounts:
          - name: mysql-storage
            mountPath: /var/lib/mysql
            subPath: mysql
          - name: init-sql
            mountPath: /docker-entrypoint-initdb.d/init.sql
            subPath: init.sql  # Mount the init.sql file from ConfigMap into the expected directory
        resources:
          requests:
            cpu: "500m"
            memory: "700M" # Set max memory to 512Mi (512MB) # Max memory (512MB)
      volumes:
      - name: mysql-storage
        persistentVolumeClaim:
          claimName: aki-detection-state
      - name: init-sql
        configMap:
          name: mysql-init-sql  # Reference the ConfigMap that contains the init.sql file
          
        
--- 
apiVersion: apps/v1
kind: Deployment
metadata:
  name: aki-detection
  namespace: europe
spec:
  replicas: 1
  strategy:
    type: Recreate
  selector:
    matchLabels:
      app: aki-detection
  template:
    metadata:
      labels:
        app: aki-detection
    spec:
      containers:
      - name: aki-detection
        image: imperialswemlsspring2025.azurecr.io/coursework4-europe
        command: []  # Specify the command if needed
        args:
          - "--history=/aki-system/data/history.csv"
        env:
          - name: MLLP_ADDRESS
            value: "europe-simulator.coursework4:8440"
          - name: PAGER_ADDRESS
            value: "europe-simulator.coursework4:8441"
          - name: MYSQL_HOST
            value: "mysql"
          - name: MYSQL_PORT
            value: "3306"
          - name: MYSQL_DB
            value: "hospital_db"
          - name: MYSQL_USER
            value: "user"
          - name: MYSQL_PASSWORD
            value: "password"
        ports:
          - name: http
            containerPort: 8000
        volumeMounts:
          - mountPath: "/aki-system/data"
            name: hospital-history
            readOnly: true
          - mountPath: "/aki-system/state"
            name: app-storage
        resources:
          requests:
            cpu: "500m"     # Use only 750m, since MySQL is using 250m
            memory: "250M" # Use available memory
      initContainers:
      - name: copy-hospital-history
        image: imperialswemlsspring2025.azurecr.io/coursework4-history
        volumeMounts:
          - mountPath: "/data"
            name: hospital-history
        resources:
          requests:
            cpu: "500m"     # Use only 750m, since MySQL is using 250m
            memory: "250M" # Use available memory

      volumes:
      - name: hospital-history
        emptyDir:
          sizeLimit: 50Mi
      - name: app-storage
        persistentVolumeClaim:
          claimName: aki-detection-state

