version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'

    ports:
      # <Port exposed> : <MySQL Port running inside container>
      - '3306:3306'
    expose:
      # Opens port 3306 on the container
      - '3306'
      # Where our data will be persisted
    volumes:
      - my-db:/var/lib/mysql
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql
    command: ["bash", "-c", "docker-entrypoint.sh mysqld & sleep 10 && mysql -uroot -p$MYSQL_ROOT_PASSWORD db < /docker-entrypoint-initdb.d/init.sql && python3 /app/feed_database.py && wait"]

    
  aki-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aki-system
    networks:
      - my_network
    logging:
      driver: "local"
    volumes:
      - ./logs/aki-system.log:/var/log/aki-system.log

# Names our volume
volumes:
  my-db:


networks:
  my_network:
    driver: bridge # README: Currently we initialise the db, create the tables, but I'm not able to use the script to feed it smh