version: '3.8'
services:
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_DATABASE: 'hospital_db'
      MYSQL_USER: 'user'
      MYSQL_PASSWORD: 'password'
      MYSQL_ROOT_PASSWORD: 'password'
    ports:
      - '3306:3306'
    expose:
      - '3306'
    command: --local-infile=1
    volumes:
      - my-db:/var/lib/mysql  # Persistent storage for MySQL data
      - ./database/init.sql:/docker-entrypoint-initdb.d/init.sql  # Runs SQL script on first startup

  aki-system:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: aki-system
    networks:
      - my_network
    logging:
      driver: "local"
    volumes:
      - ./logs/aki-system.log:/var/log/aki-system.log
    depends_on:
      - db  # Ensure database starts before aki-system

volumes:
  my-db:

networks:
  my_network:
    driver: bridge
